### ISSUE TITLE
Meta data for MoviesDB

### ISSUE THREAD

**Issue by adadesions** [adadesions/MovieDB-TOT-1#1]
# Need more information about movie data such as
- id
- movie_name
- rating (popular)
- movie_rate (X, R, 7+)
- genre
...

**I really need helps from all of you to complete the meta data**

**Comment by kanjanv** [comment]
- director 
 - actor
 - description

**Comment by Karlos911** [comment]
- price
- category
- isActive
- updateBy
- updateDate
- creatBy
- creatDate

**Comment by Patchara-k** [comment]
:grinning: movie_photo 
:smile: movie_trailer
:grinning: movie_time (ความยาวหนัง เช่น 120 นาที)
:smile: reviewer
:grinning: country

**Comment by Karlos911** [comment]
**Example**
MovieName: STAR WARS
MovieInfo: When it's discovered that the evil Emperor Palpatine did not die at the hands of Darth Vader...
Rating:	PG-13 (Sci-Fi Violence and Action)
Genre:	Adventure, Sci Fi, Action, Fantasy
Original Language:	English
Director:	J.J. Abrams
Producer:	Kathleen Kennedy, J.J. Abrams, Michelle Rejwan
Writer:	Chris Terrio, J.J. Abrams
Release Date (Theaters):	Dec 20, 2019  Wide
Release Date (Streaming):	Dec 20, 2019
Runtime:	2h 22m
Production Co:	Lucasfilm Ltd., Bad Robot
Sound Mix:	Dolby Atmos, Dolby Digital, DTS

**Comment by kanjanv** [comment]
Data format
{
"id":  srting,
        "movie_name": string,
        "director": string,
        "artist": string,
        "year": string,
        "description": string ,
}

**Comment by lnwdevze** [comment]
{
	"movies": [
		{
			"id" : 1,
			"movie_name": "The Matrix",
			"movie_genre": "Action",
			"rating_IMDB": "9.5",
			"rating_tomato": "8.9",
			"director": "Russ",
			"actors": ["A", "B", "C"],
			"poster": "https://movielab.com/ml/images/54651321.jpg",
			"isStatus": 1,
			"create_at": "2020-11-03 13:25:45",
			"update_at": "2020-11-03 13:25:45"
		},
		{
			"id" : 2,
			"movie_name": "The Witches",
			"movie_genre": "Comady",
			"rating_IMDB": "8.5",
			"rating_tomato": "8.2",
			"director": "โรเบิร์ต เซเม็กคิส",
			"actors": ["แอนน์ แฮททาเวย์", "ออคตาเวีย สเปนเซอร์", "สแตนลีย์ ทุซซี่"],
			"poster": "https://movielab.com/ml/images/54651321.jpg",
			"isStatus": 1,
			"create_at": "2020-11-03 13:30:00",
			"update_at": "2020-11-03 13:30:00"
		},
		{
			"id" : 3,
			"movie_name": "Ghosts of War",
			"movie_genre": "Horror",
			"rating_IMDB": "7.5",
			"rating_tomato": "7.9",
			"director": "Russ",
			"actors": ["เบรนตัน เทวตส์", "ไคลี่ กอลเนอร์", "อลัน ริตช์สัน"],
			"poster": "https://movielab.com/ml/images/54651321.jpg",
			"isStatus": 1,
			"create_at": "2020-11-03 13:38:20",
			"update_at": "2020-11-03 13:38:20"
		}
	]
}

**Comment by adadesions** [comment]
**In conclusion, the data format is**

{

"id": string, # id > 0 and id is natural number

"movic_name": string,

"movie_genre": string,

"artist": string,

"year": "string,

}
