### ISSUE TITLE
Need someone to write the README.md

### ISSUE THREAD

**Issue by adadesions** [adadesions/MovieDB-TOT-1#3]
**1. Contribution term
2. The location of the JSON file**

**Comment by Karlos911** [comment]
i do

**Comment by adadesions** [comment]
> i do

Good jobs, thanks for dedicated yourself to our country.

**Comment by adadesions** [comment]
**The readme was submitted  but, I need more styles with Markdown syntax.
Any one can work on it just let me know ^^**

Thanks for  your helps,
@Karlos911

**Comment by Karlos911** [comment]
I'll take care of it.
